spring:
  application:
    name: secretsanta

  datasource:
    url: jdbc:mysql://localhost:3306/secretsanta_db?useSSL=false&serverTimezone=UTC
    username: root
    password: orange
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
         
